#!/bin/bash
# Run tun-adapter with root privileges
# This script is auto-generated by the dashboard
cd "/Users/zhanghonghao/Desktop/SimplePlanePlatform"
echo "Starting tun-adapter..."
sudo "/Users/zhanghonghao/Desktop/SimplePlanePlatform/tun-adapter/target/release/tun-adapter" -c "/Users/zhanghonghao/Desktop/SimplePlanePlatform/tun-adapter/config/tun.toml"
